### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by TahjDev** [tasangpo/Splitzies#1]
- Can you add friends or add friends to groups? Im a bit confused with that bullet.

**Comment by tasangpo** [comment]
Add friends and groups are two separate modules it looks like. You can add
friends like a regular friends list and remove them.
The group is creating a group of people, not necessarily friends that you
split bills regularly with.

**Comment by TahjDev** [comment]
Ok I see. Also I dont see anything about errors inside of the User Auth MVP, what will happen when a user tries to sign up or login with the wrong user Input?

**Comment by tasangpo** [comment]
I will update it so it will give an error message.
