### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by TahjDev** [tasangpo/Splitzies#2]
- Will you need to look up a user by their email when they login, if so it needs an index?
- Column names should get back ticks when they're used in bullet points.
- When you do split a bill how are you keeping up with how much each person is gonna pay if its not equal?
- You need to bullet which table each foreign key references underneath the table
- Each foreign key needs to be indexed, to have a faster look up time when you grab those associations, if you're adding an index to pair for unique pair then you dont need to an index to the first foreign key in the brackets [first_index, second_index]
- You need some database constraints so people cant be friends with the same person same goes for group friends and expense_users. If there shouldn't be any duplicate pairs.

**Comment by tasangpo** [comment]
- (When you do split a bill how are you keeping up with how much each person is gonna pay if its not equal?) I was thinking of adding a split type in the `expense-users` table. This way, an expense will have several users associated with that expense including the split type.

**Comment by tasangpo** [comment]
- (You need some database constraints so people cant be friends with the same person same goes for group friends and expense_users. If there shouldn't be any duplicate pairs.)
- I think this constraint only needs to be put on the friends table. We are allowed to create new groups with same people in it. Group name should be distinct however.

**Comment by TahjDev** [comment]
> * (You need some database constraints so people cant be friends with the same person same goes for group friends and expense_users. If there shouldn't be any duplicate pairs.)
> * I think this constraint only needs to be put on the friends table. We are allowed to create new groups with same people in it. Group name should be distinct however.

- I more or less mean people that have been added to a group shouldnt be able to be added to that same group. Can one person be added to the same group more than once?
- Just like the same person cant be added to the same expense more than once, unless they can?
- I see that split-type is a string but how will you come up with the amount that each person is being asked to pay for. If I'm only paying a dollor and someone else is paying 5 and someone else is paying 3. All those different amounts for each person would need to be kept up with? Unless im understanding it wrong?

**Comment by tasangpo** [comment]
Yea, you are right regarding the group. I misunderstood your comment.

Regarding the split type, I will need to do some deep thinking over the
break. The site gives different ways to split like by percentages, shares
or actual amounts

**Comment by TahjDev** [comment]
Yea just let me know what you come up with
